Copyright Jana Schaich Borg/Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)

# MySQL Exercise 7: Joining Tables with Inner Joins

Before completing these exercises, I strongly recommend that you watch the video called "What are Joins?" that describe what joins are, and how different types of joins work.

As one of the last building blocks we need to address our Dognition analysis questions, in this lesson we will learn how to combine tables using inner joins.

   
## 1. Inner Joins between 2 tables

To begin, load the sql library, connect to the Dognition database, and set the Dognition database as the default.

In [3]:
%load_ext sql
%sql mysql://studentuser:studentpw@localhost/dognitiondb
%sql USE dognitiondb

 * mysql://studentuser:***@localhost/dognitiondb
0 rows affected.


[]

Recall that tables in relational databases are linked through primary keys and sometimes other fields that are common to multiple tables (as is the case with our Dognition data set).  Our goal when we execute a JOIN or make a joined table is to use those common columns to let the database figure out which rows in one table match up to which rows in another table.  Once that mapping is established using at least one common field or column, the database can pull any columns you want out of the mapped, or joined, tables and output the matched data to one common table.

An inner join is a join that outputs only rows that have an exact match in both tables being joined:

<img src="https://duke.box.com/shared/static/xazeqtyq6bjo12ojvgxup4bx0e9qcn5d.jpg" width=400 alt="INNER_JOIN" />

To illustrate how this works, let's find out whether dog owners that are particularly surprised by their dog's performance on Dognition tests tend to own similar breeds (or breed types, or breed groups) of dogs.  There are many ways to address this question, but let's start by focusing on the dog owners who provided at least 10 ratings for one or more of their dogs in the ratings table. Of these owners, which 200 owners reported the highest average amount of surprise at their dog's performance, and what was the breed, breed_type, and breed_group of each of these owner's dog?

The surprise ratings are stored in the reviews table.  The dog breed information is provided in the dogs table.  There are two columns that are common to both tables: user_guid and dog_guid. How do we use the common columns to combine information from the two tables? 

To join the tables, you can use a WHERE clause and add a couple of details to the FROM clause so that the database knows from what table each field in your SELECT clause comes.  

First, start by adding all the columns we want to examine to the SELECT statement:

```mySQL
SELECT dog_guid AS DogID, user_guid AS UserID, AVG(rating) AS AvgRating, 
       COUNT(rating) AS NumRatings, breed, breed_group, breed_type
```
then list all the tables from which the fields we are interested in come, separated by commas (with no comma at the end of the list):

```mySQL
FROM dogs, reviews
```
then add the other restrictions:

```mySQL
GROUP BY user_guid, dog_guid, breed, breed_group, breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

**Try running this query and see what happens:**



In [2]:
%%sql

UsageError: %%sql is a cell magic, but the cell body is empty. Did you mean the line magic %sql (single %)?


You should receive an error message stating that the identity of dog_guid and user_guid in the field list is ambiguous. The reason is that the column title exists in both tables, and MySQL doesn't know which one we want. We have to specify the table name before stating the field name, and separate the two names by a period <mark>(NOTE: read this entire section before deciding whether you want to execute this query)<mark\>:

```mySQL
SELECT dogs.dog_guid AS DogID, dogs.user_guid AS UserID, AVG(reviews.rating) AS AvgRating,     
       COUNT(reviews.rating) AS NumRatings, dogs.breed, dogs.breed_group, dogs.breed_type
FROM dogs, reviews
GROUP BY dogs.user_guid, dogs.dog_guid, dogs.breed, dogs.breed_group, dogs.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```


You can also take advantage of aliases so that you don't have to write out the name of the tables each time.  Here I will introduce another syntax for aliases that omits the AS completely.  In this syntax, the alias is whatever word (or phrase, if you use quotation marks) follows immediately after the field or table name, separated by a space. Some people find it easier to read queries if you use the syntax without an AS to create table aliases, but retain the syntax with an AS to create field aliases (but both syntaxes work for field aliases and table aliases).  So we could write:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
GROUP BY DogID, UserID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

I am tempted to tell you to run this query so that you will see what happens, but instead, I will explain what will happen and let you decide if you want to see what the output looks...and feels...like.  
      
There is nothing built into the database table definitions that can instruct the server how to combine the tables on its own (remember, this is how relational databases save space and remain flexible).  Further, the query as written does not tell the database how the two tables are related.  As a consequence, rather than match up the two tables according to the values in the user_id and/or dog_id column, the database will do the only thing it knows how to do which is output every single combination of the records in the dogs table with the records in the reviews table.  In other words, every single row of the dogs table will get paired with every single row of the reviews table.  This is known as a Cartesian product.  Not only will it be a heavy burden on the database to output a table that has the full length of one table multiplied times the full length of another (and frustrating to you, because the query would take a very long time to run), the output would be close to useless.

To prevent this from happening, tell the database how to relate the tables in the WHERE clause:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

To be very careful and exclude any incorrect dog_guid or user_guid entries, you can include both shared columns in the WHERE clause:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

**Try running this query now:**

In [4]:
%%sql
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 5;

 * mysql://studentuser:***@localhost/dognitiondb
5 rows affected.


[('fdbf39f8-7144-11e5-ba71-058fbc01cf0b', 'ce987914-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 12, 'Canaan Dog', 'Herding', 'Pure Breed'),
 ('fdc09a82-7144-11e5-ba71-058fbc01cf0b', 'ce99bb12-7144-11e5-ba71-058fbc01cf0b', Decimal('5.0000'), 10, 'Golden Doodle', None, 'Popular Hybrid'),
 ('fdbef330-7144-11e5-ba71-058fbc01cf0b', 'ce984d2c-7144-11e5-ba71-058fbc01cf0b', Decimal('4.5385'), 13, 'Havanese', 'Toy', 'Pure Breed'),
 ('fdc0518a-7144-11e5-ba71-058fbc01cf0b', 'ce99661c-7144-11e5-ba71-058fbc01cf0b', Decimal('3.7333'), 15, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd684cf6-7144-11e5-ba71-058fbc01cf0b', 'ce473856-7144-11e5-ba71-058fbc01cf0b', Decimal('3.7222'), 18, 'Labrador Retriever', 'Sporting', 'Pure Breed')]

The query should execute quickly.  This would NOT have been the case if you did not include the WHERE clause to combine the two tables. If you accidentally request a Cartesian product from datasets with billions of rows, you could be waiting for your query output for days (and will probably get in trouble with your database administrator).  <mark>So always remember to tell the database how to join your tables!</mark>

Let's examine our joined table a bit further.  The joined table outputted by the query above should have 38 rows, despite the fact that we set our LIMIT at 200.  The reason for this is that it turns out that a relatively small number of customers provided 10 or more reviews.  If you remove the HAVING and LIMIT BY clause from the query, you should end up with 389 rows.  **Go ahead and try it:**


In [6]:
%%sql
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
ORDER BY AvgRating DESC
LIMIT 5;

 * mysql://studentuser:***@localhost/dognitiondb
5 rows affected.


[('fdbf178e-7144-11e5-ba71-058fbc01cf0b', 'ce986546-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Airedale Terrier', 'Terrier', 'Pure Breed'),
 ('fdc057ac-7144-11e5-ba71-058fbc01cf0b', 'ce996b9e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc19554-7144-11e5-ba71-058fbc01cf0b', 'ce9a8a24-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdbedd14-7144-11e5-ba71-058fbc01cf0b', 'ce975994-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc147ac-7144-11e5-ba71-058fbc01cf0b', 'ce9a545a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Tibetan Terrier', 'Non-Sporting', 'Pure Breed')]

It's clear from looking at this output that (A) not many customers provided ratings, and (B) when they did, they usually were not very surprised by their dog's performance.  Therefore, these ratings are probably not going to provide a lot of instructive insight into how to improve Dognition's completion rate.  However, the ratings table still provides a great opportunity to illustrate the results of different types of joins.  

To help prepare us for this:

**Questions 1-4:  How many unique dog_guids and user_guids are there in the reviews and dogs table independently?**  

In [8]:
%%sql
SELECT COUNT(DISTINCT user_guid) as num_users, COUNT(DISTINCT dog_guid) as num_dogs
FROM dogs;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.


[(30967, 35050)]

In [9]:
%%sql
SELECT COUNT(DISTINCT user_guid) as num_users, COUNT(DISTINCT dog_guid) as num_dogs
FROM reviews;

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.


[(5586, 5991)]

In [74]:
%%sql
SELECT COUNT(d.dog_guid) as num_dogs
FROM dogs d, reviews r
WHERE d.dog_guid = r.dog_guid

 * mysql://studentuser:***@localhost/dognitiondb
1 rows affected.


[(1522,)]

These counts indicate some important things:

+ Many customers in both the reviews and the dogs table have multiple dogs
+ There are many more unique dog_guids and user_guids in the dogs table than the reviews table
+ There are many more unique dog_guids and user_guids in the reviews table than in the output of our inner join

Let's test one more thing.  
   
**Try the inner join query once with just the dog_guid or once with just the user_guid clause in the WHERE statement:**



In [78]:
%%sql
SELECT d.user_guid as num_users, d.dog_guid as num_dogs
FROM dogs d, reviews r
WHERE d.dog_guid = r.dog_guid
GROUP BY d.user_guid;

 * mysql://studentuser:***@localhost/dognitiondb
389 rows affected.


[('ce138268-7144-11e5-ba71-058fbc01cf0b', 'fd27dc52-7144-11e5-ba71-058fbc01cf0b'),
 ('ce2261a2-7144-11e5-ba71-058fbc01cf0b', 'fd3fd514-7144-11e5-ba71-058fbc01cf0b'),
 ('ce25f772-7144-11e5-ba71-058fbc01cf0b', 'fd427a76-7144-11e5-ba71-058fbc01cf0b'),
 ('ce26de3a-7144-11e5-ba71-058fbc01cf0b', 'fd439f3c-7144-11e5-ba71-058fbc01cf0b'),
 ('ce275612-7144-11e5-ba71-058fbc01cf0b', 'fd442826-7144-11e5-ba71-058fbc01cf0b'),
 ('ce28392e-7144-11e5-ba71-058fbc01cf0b', 'fd450d2c-7144-11e5-ba71-058fbc01cf0b'),
 ('ce287fba-7144-11e5-ba71-058fbc01cf0b', 'fd45992c-7144-11e5-ba71-058fbc01cf0b'),
 ('ce416692-7144-11e5-ba71-058fbc01cf0b', 'fd675a08-7144-11e5-ba71-058fbc01cf0b'),
 ('ce471e48-7144-11e5-ba71-058fbc01cf0b', 'fd681c5e-7144-11e5-ba71-058fbc01cf0b'),
 ('ce473856-7144-11e5-ba71-058fbc01cf0b', 'fd684cf6-7144-11e5-ba71-058fbc01cf0b'),
 ('ce4738c4-7144-11e5-ba71-058fbc01cf0b', 'fd684d5a-7144-11e5-ba71-058fbc01cf0b'),
 ('ce66aaec-7144-11e5-ba71-058fbc01cf0b', 'fd6913ac-7144-11e5-ba71-058fbc01cf0b'),
 ('ce675b68-7144-11e5-ba71-058fbc01cf0b', 'fd6a5654-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6ccc1a-7144-11e5-ba71-058fbc01cf0b', 'fd6a73b4-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6cd804-7144-11e5-ba71-058fbc01cf0b', 'fd6aabd6-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6ce394-7144-11e5-ba71-058fbc01cf0b', 'fd6a6590-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6cf370-7144-11e5-ba71-058fbc01cf0b', 'fd6a72e2-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6cf3fc-7144-11e5-ba71-058fbc01cf0b', 'fd6a7490-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6d4e9c-7144-11e5-ba71-058fbc01cf0b', 'fd6abc8e-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6fadfe-7144-11e5-ba71-058fbc01cf0b', 'fd6e49da-7144-11e5-ba71-058fbc01cf0b'),
 ('ce6fede6-7144-11e5-ba71-058fbc01cf0b', 'fd6ea538-7144-11e5-ba71-058fbc01cf0b'),
 ('ce701492-7144-11e5-ba71-058fbc01cf0b', 'fd6eb0aa-7144-11e5-ba71-058fbc01cf0b'),
 ('ce7054fc-7144-11e5-ba71-058fbc01cf0b', 'fd6f1360-7144-11e5-ba71-058fbc01cf0b'),
 ('ce710154-7144-11e5-ba71-058fbc01cf0b', 'fd6fd44e-7144-11e5-ba71-058fbc01cf0b'),
 ('ce715af0-7144-11e5-ba71-058fbc01cf0b', 'fd702994-7144-11e5-ba71-058fbc01cf0b'),
 ('ce7212a6-7144-11e5-ba71-058fbc01cf0b', 'fd7104ae-7144-11e5-ba71-058fbc01cf0b'),
 ('ce73cb6e-7144-11e5-ba71-058fbc01cf0b', 'fd732310-7144-11e5-ba71-058fbc01cf0b'),
 ('ce758990-7144-11e5-ba71-058fbc01cf0b', 'fd754000-7144-11e5-ba71-058fbc01cf0b'),
 ('ce7b055a-7144-11e5-ba71-058fbc01cf0b', 'fd41bca8-7144-11e5-ba71-058fbc01cf0b'),
 ('ce88940e-7144-11e5-ba71-058fbc01cf0b', 'fdc1fddc-7144-11e5-ba71-058fbc01cf0b'),
 ('ce958a74-7144-11e5-ba71-058fbc01cf0b', 'fdc13640-7144-11e5-ba71-058fbc01cf0b'),
 ('ce96a01c-7144-11e5-ba71-058fbc01cf0b', 'fdbf0e2e-7144-11e5-ba71-058fbc01cf0b'),
 ('ce96c768-7144-11e5-ba71-058fbc01cf0b', 'fdc1c880-7144-11e5-ba71-058fbc01cf0b'),
 ('ce975994-7144-11e5-ba71-058fbc01cf0b', 'fdbedd14-7144-11e5-ba71-058fbc01cf0b'),
 ('ce9782c0-7144-11e5-ba71-058fbc01cf0b', 'fdbee278-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97a6b0-7144-11e5-ba71-058fbc01cf0b', 'fdc0bb34-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97dd60-7144-11e5-ba71-058fbc01cf0b', 'fdbe74d2-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97de1e-7144-11e5-ba71-058fbc01cf0b', 'fdbe7630-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97df36-7144-11e5-ba71-058fbc01cf0b', 'fdbe78ec-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97df9a-7144-11e5-ba71-058fbc01cf0b', 'fdbe7a40-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e04e-7144-11e5-ba71-058fbc01cf0b', 'fdbe7b9e-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e0b2-7144-11e5-ba71-058fbc01cf0b', 'fdbe7d56-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e10c-7144-11e5-ba71-058fbc01cf0b', 'fdbe7cac-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e166-7144-11e5-ba71-058fbc01cf0b', 'fdbf4588-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e2ec-7144-11e5-ba71-058fbc01cf0b', 'fdbe8044-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e3aa-7144-11e5-ba71-058fbc01cf0b', 'fdbe81a2-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e4cc-7144-11e5-ba71-058fbc01cf0b', 'fdbe8210-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e6a2-7144-11e5-ba71-058fbc01cf0b', 'fdbe844a-7144-11e5-ba71-058fbc01cf0b'),
 ('ce97e97c-7144

In [80]:
%%sql
SELECT d.user_guid as num_users, COUNT(d.dog_guid) as num_dogs
FROM dogs d, reviews r
WHERE d.user_guid = r.user_guid
GROUP BY d.user_guid;

 * mysql://studentuser:***@localhost/dognitiondb
5586 rows affected.


[('ce134492-7144-11e5-ba71-058fbc01cf0b', 9),
 ('ce137868-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce137f20-7144-11e5-ba71-058fbc01cf0b', 30),
 ('ce137fca-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce138268-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce1385c4-7144-11e5-ba71-058fbc01cf0b', 8),
 ('ce1387cc-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce2232cc-7144-11e5-ba71-058fbc01cf0b', 34),
 ('ce224208-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce224cee-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce2261a2-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce226576-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce23ec8e-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce242e74-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce2434e6-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce24476a-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce244fd0-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce2461dc-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce24a4ee-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce24c50a-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce24c8a2-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce24d130-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce250e48-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce2514c4-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce251690-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce251af0-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce252c98-7144-11e5-ba71-058fbc01cf0b', 9),
 ('ce253cf6-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce254534-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce25482c-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce2554ca-7144-11e5-ba71-058fbc01cf0b', 12),
 ('ce257d2e-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce2581a2-7144-11e5-ba71-058fbc01cf0b', 16),
 ('ce258896-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce25a466-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce25a6f0-7144-11e5-ba71-058fbc01cf0b', 8),
 ('ce25b9d8-7144-11e5-ba71-058fbc01cf0b', 20),
 ('ce25c2ac-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce25f0c4-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce25f772-7144-11e5-ba71-058fbc01cf0b', 12),
 ('ce25f9a2-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce25fac4-7144-11e5-ba71-058fbc01cf0b', 5),
 ('ce260168-7144-11e5-ba71-058fbc01cf0b', 20),
 ('ce261aa4-7144-11e5-ba71-058fbc01cf0b', 5),
 ('ce261bd0-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce261edc-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce262364-7144-11e5-ba71-058fbc01cf0b', 100),
 ('ce264330-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce2673f0-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce267e18-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce2684b2-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce268c1e-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce26ad84-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce26b266-7144-11e5-ba71-058fbc01cf0b', 105),
 ('ce26de3a-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce26edbc-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce27023e-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce272124-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce275612-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce275676-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce275f22-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce277962-7144-11e5-ba71-058fbc01cf0b', 9),
 ('ce277e30-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce278236-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce27928a-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce279956-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce27c0ac-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce27c250-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce27cf02-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce27e262-7144-11e5-ba71-058fbc01cf0b', 12),
 ('ce27e910-7144-11e5-ba71-058fbc01cf0b', 5),
 ('ce27eb2c-7144-11e5-ba71-058fbc01cf0b', 9),
 ('ce27ef6e-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce28392e-7144-11e5-ba71-058fbc01cf0b', 4),
 ('ce284536-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce284892-7144-11e5-ba71-058fbc01cf0b', 22),
 ('ce284b1c-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce284e5a-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce28623c-7144-11e5-ba71-058fbc01cf0b', 3),
 ('ce286868-7144-11e5-ba71-058fbc01cf0b', 2),
 ('ce287fba-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce28806e-7144-11e5-ba71-058fbc01cf0b', 1),
 ('ce28c150-7144-11e5-ba71-058fbc01cf0b', 10),
 ('ce28c2cc-7144-11e5-ba71-058fbc01cf0b', 16),
 ('ce28e3ce-7144-11e5-ba71-058fbc01cf0b', 6),
 ('ce28e61c-7144-11e5-ba71-058fbc01cf0b', 14),
 ('ce28eaa4-7144-11e5-ba71-0

When you run the query by joining on the dog_guid only, you still get 389 rows in your output.  When you run the query by joining on the user_guid only, you get 5586 rows in your output.  This means that:

+ All of the user_guids in the reviews table are in the dogs table
+ Only 389 of the over 5000 dog_guids in the reviews table are in the dogs table

Perhaps most importantly for our current purposes, these COUNT queries show you that <mark>*inner joins only output the data from rows that have equivalent values in both tables being joined*.</mark>  If you wanted to include all the dog_guids or user_guids in one or both of the tables, you would have to use an outer join, which we will practice in the next lesson.

Try an inner join on your own.  
   

**Question 5: How would you extract the user_guid, dog_guid, breed, breed_type, and breed_group for all animals who completed the "Yawn Warm-up" game (you should get 20,845 rows if you join on dog_guid only)?**

In [31]:
%%sql 
SELECT d.dog_guid, d.user_guid, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c
WHERE d.dog_guid = c.dog_guid AND c.test_name = 'Yawn Warm-up'
LIMIT 3;

 * mysql://studentuser:***@localhost/dognitiondb
3 rows affected.


[('fd27b86c-7144-11e5-ba71-058fbc01cf0b', 'ce135e14-7144-11e5-ba71-058fbc01cf0b', 'Shih Tzu', 'Pure Breed', 'Toy'),
 ('fd27bbbe-7144-11e5-ba71-058fbc01cf0b', 'ce135f2c-7144-11e5-ba71-058fbc01cf0b', 'Mixed', "Mixed Breed/ Other/ I Don't Know", None),
 ('fd27ba1a-7144-11e5-ba71-058fbc01cf0b', 'ce135e14-7144-11e5-ba71-058fbc01cf0b', 'Shih Tzu', 'Pure Breed', 'Toy')]

## 2. Joining More than 2 Tables

In theory, you can join as many tables together as you want or need.  To join multiple tables you take the same approach as we took when we were joining two tables together: list all the fields you want to extract in the SELECT statement, specify which table they came from in the SELECT statement, list all the tables from which you will need to extract the fields in the FROM statement, and then tell the database how to connect the tables in the WHERE statement.

To extract the user_guid, user's state of residence, user's zip code, dog_guid, breed, breed_type, and breed_group for all animals who completed the "Yawn Warm-up" game, you might be tempted to query:

```mySQL
SELECT c.user_guid AS UserID, u.state, u.zip, d.dog_guid AS DogID, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid 
   AND c.user_guid=u.user_guid
   AND c.test_name="Yawn Warm-up";
```
This query focuses the relationships primarily on the complete_tests table.  However, it turns out that our Dognition dataset has only NULL values in the user_guid column of the complete_tests table.  If you were to execute the query above, you would not get an error message, but your output would have 0 rows.  However, the power of relational databases will come in handy here.  You can use the dogs table to link the complete_tests and users table (pay attention to the difference between the WHERE statement in this query vs. the WHERE statement in the query above):

```mySQL
SELECT d.user_guid AS UserID, u.state, u.zip, d.dog_guid AS DogID, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid 
   AND d.user_guid=u.user_guid
   AND c.test_name="Yawn Warm-up";
```

Of note, joins are very resource intensive, so try not to join unnecessarily.  In general, the more joins you have to execute, the slower your query performance will be.

**Question 6: How would you extract the user_guid, membership_type, and dog_guid of all the golden retrievers who completed at least 1 Dognition test (you should get 711 rows)?**

In [17]:
%%sql
SELECT DISTINCT d.user_guid, u.membership_type, d.dog_guid, d.breed
FROM users u, dogs d, complete_tests c
WHERE d.user_guid = u.user_guid
    AND d.dog_guid = c.dog_guid
    AND d.breed = 'Golden Retriever' LIMIT 3;

 * mysql://studentuser:***@localhost/dognitiondb
3 rows affected.


[('ce135ab8-7144-11e5-ba71-058fbc01cf0b', 1, 'fd27b6b4-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce13507c-7144-11e5-ba71-058fbc01cf0b', 1, 'fd27b79a-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce1389d4-7144-11e5-ba71-058fbc01cf0b', 1, 'fd27efb2-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever')]

## Practice inner joining your own tables!

**Question 7: How many unique Golden Retrievers who live in North Carolina are there in the Dognition database (you should get 30)?**



In [28]:
%%sql
SELECT DISTINCT d.dog_guid, u.state, d.breed
FROM dogs d, users u
WHERE d.user_guid = u.user_guid
    AND u.state = 'NC'
    AND d.breed = 'Golden Retriever'
ORDER BY d.dog_guid ASC
LIMIT 5;

 * mysql://studentuser:***@localhost/dognitiondb
5 rows affected.


[('fd27ec1a-7144-11e5-ba71-058fbc01cf0b', 'NC', 'Golden Retriever'),
 ('fd40f822-7144-11e5-ba71-058fbc01cf0b', 'NC', 'Golden Retriever'),
 ('fd411b0e-7144-11e5-ba71-058fbc01cf0b', 'NC', 'Golden Retriever'),
 ('fd418b02-7144-11e5-ba71-058fbc01cf0b', 'NC', 'Golden Retriever'),
 ('fd43d9de-7144-11e5-ba71-058fbc01cf0b', 'NC', 'Golden Retriever')]

**Question 8: How many unique customers within each membership type provided reviews (there should be 2900 in the membership type with the greatest number of customers, and 15 in the membership type with the fewest number of customers if you do NOT include entries with NULL values in their ratings field)?**

In [34]:
%%sql
SELECT COUNT(DISTINCT u.user_guid) AS count_reviews, u.membership_type
FROM users u, reviews r
WHERE u.user_guid = r.user_guid
    AND r.rating IS NOT NULL
GROUP BY u.membership_type;

 * mysql://studentuser:***@localhost/dognitiondb
5 rows affected.


[(2900, 1), (1120, 2), (238, 3), (816, 4), (15, 5)]

**Question 9: For which 3 dog breeds do we have the greatest amount of site_activity data, (as defined by non-NULL values in script_detail_id)(your answers should be "Mixed", "Labrador Retriever", and "Labrador Retriever-Golden Retriever Mix"?**

In [51]:
%%sql
SELECT d.breed, COUNT(s.script_detail_id)
FROM dogs d, site_activities s
WHERE d.dog_guid = s.dog_guid
    AND s.script_detail_id IS NOT NULL
GROUP BY d.breed
ORDER BY COUNT(s.script_detail_id) DESC
LIMIT 3;

 * mysql://studentuser:***@localhost/dognitiondb
3 rows affected.


[('Mixed', 93415),
 ('Labrador Retriever', 38804),
 ('Labrador Retriever-Golden Retriever Mix', 27498)]

**Practice any other inner joins you would like to try here!**